apiVersion: batch/v1
kind: Job
metadata:
  name: distcc-client-job
spec:
  template:
    spec:
      containers:
      - name: client
        image: distcc-ccache:local
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
        - |
          /usr/local/bin/generate_distcc_hosts.sh make -j16 CC="distcc gcc"
        env:
        - name: CCACHE_DIR
          value: /ccache
        volumeMounts:
        - name: ccache
          mountPath: /ccache
      restartPolicy: Never
      volumes:
      - name: ccache
        persistentVolumeClaim:
          claimName: hcn-nfs-pvc
