apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distccd-amd64
  namespace: devtools
  labels:
    app: distcc
    kubernetes.io/arch: amd64
spec:
  selector:
    matchLabels:
      app: distcc
      role: amd64-native
  template:
    metadata:
      labels:
        app: distcc
        role: amd64-native
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: distccd
        image: registry/distccd-amd64-native:latest
        command: ["distccd"]
        args:
          - "--no-detach"
          - "--allow=10.0.0.0/8"
        ports:
        - containerPort: 3632
          hostPort: 3632
          protocol: TCP
