apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distccd-arm64
  namespace: devtools
  labels:
    app: distcc
    kubernetes.io/arch: arm64
spec:
  selector:
    matchLabels:
      app: distcc
      role: arm64-native
  template:
    metadata:
      labels:
        app: distcc
        role: arm64-native
    spec:
      nodeSelector:
        kubernetes.io/arc: arm64
      containers:
      - name: distccd
        image: registry.registry.svc.cluster.local:5000/distccd-arm64-native:latest
        ports:
        - containerPort: 3632
          hostPort: 3632
          protocol: TCP
