apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distccd-native
  namespace: devtools
  labels:
    app: distcc
spec:
  selector:
    matchLabels:
      app: distcc
      role: native
  template:
    metadata:
      labels:
        app: distcc
        role: native
    spec:
      containers:
      - name: distccd
        image: registry/distccd-native:latest
        command: ["distccd"]
        args:
          - "--no-detach"
          - "--allow=10.0.0.0/8"
        ports:
        - containerPort: 3632
          hostPort: 3632
          protocol: TCP
