apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distccd-arm64
  namespace: devtools
  labels:
    app: distcc
    kubernetes.io/arch: arm64
spec:
  selector:
    matchLabels:
      app: distcc
      role: arm64-native
  template:
    metadata:
      labels:
        app: distcc
        role: arm64-native
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: distccd
        image: registry/distccd-arm64-native:latest
        command: ["distccd"]
        args:
          - "--daemon"
          - "--allow=10.0.0.0/8"
        ports:
        - containerPort: 3632
          hostPort: 3632
          protocol: TCP
