apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distcc
  namespace: devtools
  labels:
    app: distcc
spec:
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      labels:
        app: distcc
      spec:
        template:
          spec:
            containers:
            - name: distccd
              image: 192.168.0.104:30000/distcc:latest
              command: ["distccd"]
              args:
                - "--daemon"
                - "--allow=10.0.0.0/8"
              ports:
              - containerPort: 3632
                hostPort: 3632
