apiVersion: v1
kind: Service
metadata:
  name: distcc-headless
  namespace: devtools
spec:
  clusterIP: None
  selector:
    app: distcc
  ports:
  - port: 3632
    targetPort: 3632
    protocol: TCP
