apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distccd-amd64
  namespace: devtools
  labels:
    app: distcc
    kubernetes.io/arch: amd64
spec:
  selector:
    matchLabels:
      app: distcc
      role: amd64-native
  template:
    metadata:
      labels:
        app: distcc
        role: amd64-native
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        distccd: "true"
      containers:
      - name: distccd
        image: 192.168.0.104:30000/distccd-amd64-native:latest
        command: ["distccd"]
        args:
          - "--no-detach"
          - "--allow=0.0.0.0/0"
        ports:
        - containerPort: 3632
          hostPort: 3632
          protocol: TCP
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
