apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distccd-cross
  namespace: devtools
  labels:
    app: distcc
    kubernetes.io/arch: amd64
    cross: arm64
spec:
  selector:
    matchLabels:
      app: distcc
      role: arm64-cross
  template:
    metadata:
      labels:
        app: distcc
        role: arm64-cross
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        cpu: high
      containers:
      - name: distccd
        image: registry/distccd-amd64-cross:latest
        command: ["distccd"]
        args:
          - "--no-detach"
          - "--allow=10.0.0.0/8"
        ports:
        - containerPort: 3633
          hostPort: 3633
          protocol: TCP
