FROM ubuntu:22.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    apt-get install -y -qq distcc gcc-aarch64-linux-gnu g++-aarch64-linux-gnu && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Point distccd to the aarch64 cross compiler
ENV PATH="/usr/aarch64-linux-gnu/bin:/usr/bin:$PATH"
ENV ALLOW=0.0.0.0/0

RUN useradd --no-create-home distcc
USER distcc

EXPOSE 3632

CMD ["distccd","--no-detach","--daemon","--jobs","$(nproc)","--allow","${ALLOW}","--log-stderr"]
