FROM arm64v8/ubuntu:22.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    apt-get install -y -qq distcc gcc g++ clang && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd --no-create-home distcc
CMD ["distccd", "--daemon", "--allow=10.0.0.0/8", "--log-stderr"]
