FROM ubuntu:22.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    apt-get install -y -qq distcc gcc g++ clang && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

    ENV ALLOW 10.0.0.0/8

    RUN useradd --no-create-home distcc
    USER distcc
    
    EXPOSE 3632
    
    CMD ["distccd","--no-detach","--daemon","--jobs","$(nproc)","--allow","${ALLOW}","--log-stderr"] 
