apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-esrgan
  namespace: ai
  labels:
    app: real-esrgan
spec:
  selector:
    matchLabels:
      app: real-esrgan
  template:
    metadata:
      labels:
        app: real-esrgan
    spec:
      containers:
      - name: real-esrgan
        image: registry/real-esrgan:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
      restartPolicy: Always
      nodeSelector:
        gpu-cuda: high
        cuda: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: real-esrgan-service
  namespace: ai
spec:
  selector:
    app: real-esrgan
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
