apiVersion: v1
kind: PersistentVolume
metadata:
  name: hcn-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.1
    path: /mnt/shared_storage
