apiVersion: v1
kind: PersistentVolume
metadata:
  name: hcn-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.104
    path: /mnt/shared_drive
