apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hcn-nfs-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: hcn-nfs-pv
